export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const GET_CONTACT_DETAILS = "GET_CONTACT_DETAILS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const ADD_CONTACT_TO_FAV = "ADD_CONTACT_TO_FAV";
